# 開発用Dockerfile（マルチステージの旨みがないがとりあえずマルチステージで）
# 依存パッケージのインストール
FROM node:24.8.0-slim as deps

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# 実行環境
FROM node:24.8.0-slim

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . ./

# EXPOSE 3001　　// devcontainerの機能のポートフォワードが優先されるのでコメントアウト

# CMD ["/bin/bash","./.devcontainer/entrypoint.sh"] // devcontainerのpostStartCommandでentrypoint.shを実行するのでコメントアウト
CMD ["sleep", "infinity"] // メインプロセスが終了するとコンテナ自体も終了するため、無限ループで待ち続ける
