services:
  app:
    build:
      context: .. # プロジェクトの親ディレクトリを指定
      dockerfile: .devcontainer/Dockerfile.dev
    ports:
      - 3001:3000
    volumes:
      - ..:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
volumes:
  node_modules:
